### ISSUE TITLE
libphonenumber-js Breaks bundlephobia

### ISSUE THREAD

**Issue by alanhogan** [pastelsky/bundlephobia#164] opened 2019-05-23 15:51 UTC
## Type
Bug / Feature Request

## Package name

libphonenumber-js

### Entire error (stringified) I see in my browser console
`main.bundle.js from Terser Export statement may only appear at top level [main.bundle.js:14,0]` (visible in UI when expanding stack trace)

From console: 

> Failed to load resource: the server responded with a status of 500 ()
result.js:1:13414
> 0 "main.bundle.js from Terser↵Export statement may only appear at top level [main.bundle.js:14,0]"

**Comment by pastelsky** [comment] 2019-07-23 12:59
This is caused by the fix to https://github.com/catamphetamine/libphonenumber-js/issues/239. The webpack-compiled output of this package looks like this -

```js
(function(module, exports) {

// This file is a workaround for a bug in web browsers' "native"
// ES6 importing system which is uncapable of importing "*.json" files.
// https://github.com/catamphetamine/libphonenumber-js/issues/239
export default {"versi ....   // <-------- This cannot sit inside a function 
```

**Comment by ahmedelgabri** [comment] 2019-12-05 12:44
@pastelsky I checked the library & it doesn't export the same code as you mentioned but still fails with the same error

**Comment by ipiv** [comment] 2019-12-24 07:24
From libphonenumber-js readme:
>Importing functions directly from libphonenumber-js results in using the **min** metadata

Current Webpack configuration is set to not parse .min.js files
See https://github.com/pulse-framework/pulse/pull/58

**Comment by ipiv** [comment] 2019-12-24 07:40
In this case, changing regex to `noParse: [/\.min\.js$/]` would cause "metadata.min.json" to be parsed.

**Comment by pastelsky** [comment] 2019-12-24 17:45
Closing this, should be fixed with the next version of `package-build-stats.

Thanks to @ipiv for figuring out the root cause here.

**Closed by pastelsky** 2019-12-24 17:45 UTC
Labels: build error
