### ISSUE TITLE
Force cache clean

### ISSUE THREAD

**Issue by Kelin2025** [pastelsky/bundlephobia#44] opened 2018-01-15 02:28 UTC
## Type
Feature Request

## About
I often publicate a new versions of my libraries and then I want to check its size but we need to wait a lot of time for it  
Can we have **no-cache** option or force check withour cache **if newer version is requested**?
![image](https://user-images.githubusercontent.com/4208480/34924455-793a4e16-f9b4-11e7-8c4e-bad3aabf2a72.png)
![image](https://user-images.githubusercontent.com/4208480/34924445-6f208788-f9b4-11e7-9fb0-b4917ca1a2b1.png)

**Comment by pastelsky** [comment] 2018-01-16 17:15
Hi @Kelin2025. We do not cache package searches that don't have an explicit version specified — for eg - a search for `react` is not cached, but one for `react@15.6.0` would be. Discovery of new versions should be near instantaneous as far as I can remember. 

The error in the screenshot might be caused by https://github.com/pastelsky/bundlephobia/issues/43#issuecomment-357485856 .

Let me know if this is still a issue.

**Comment by Kelin2025** [comment] 2018-01-17 18:19
I will check it on next version update

**Comment by nksfrank** [comment] 2018-02-09 10:46
We where publishing fix where we where adding react as a peerDependency to our package.
![image](https://user-images.githubusercontent.com/7352072/36024018-b795307a-0d8e-11e8-95c5-e12ca8133501.png)

But searched on our new version to soon, before it had been fully published, getting a MissingDependencyError
![image](https://user-images.githubusercontent.com/7352072/36023925-6ef7c120-0d8e-11e8-8981-84a93a5e68ed.png)

**Comment by pastelsky** [comment] 2018-02-09 11:55
What do you do see after publish?

**Comment by nksfrank** [comment] 2018-02-09 12:35
the MissingDependencyError result is from after publish

**Comment by nicolasdelfino** [comment] 2018-02-09 13:31
1.9.2 was released shortly after, this version first showed the same error (MissingDependencyError), then after a refresh it continued with resolving / bundling & minifying but sadly it got stuck on "calculating file sizes" .

**Comment by pastelsky** [comment] 2018-02-21 04:58
Just checked, we have short time cache (a few hours) for package searches that don't include a version. However, when one searches with an explicit version, this should not happen.

**Comment by ardalanamini** [comment] 2019-05-29 18:59
@pastelsky I'm searching an explicit version but still get the error `PackageVersionMismatchError`

here's the link: https://bundlephobia.com/result?p=@foxify/i18n@1.1.0

**Comment by pastelsky** [comment] 2019-05-29 19:05
The yarnpkg registry seems to be taking some time to reflect this newly
published version. Bundlephobia's search depends on its presence.

**Comment by ardalanamini** [comment] 2019-05-30 09:09
Maybe you should reconsider your registry choice, 'Cause my package's version still isn't available in yarnpkg and this could happen to other packages too

**Comment by pastelsky** [comment] 2019-09-29 10:03
This should be fixed in the next release. We'll now use npm's official registry to resolve versions. Thanks!

**Closed by pastelsky** 2019-09-29 10:03 UTC
